CREATE SEQUENCE sequence_event_service;
CREATE TABLE service_event(
    ID smallint NOT NULL DEFAULT nextval('sequence_event_service'),
    eventID int,
    ServiceID int,
    PRIMARY KEY (ID),
    FOREIGN KEY (eventID) REFERENCES events(eventID),
    FOREIGN KEY (serviceID) REFERENCES services(serviceID));

INSERT INTO service_event (eventID, serviceID)
VALUES ('1','6'),
       ('1','2'),
       ('1','3'),
       ('2','1'),
       ('2','5'),
       ('2','4'),
       ('3','1'),
       ('3','4'),
       ('3','6'),
       ('4','2'),
       ('4','3'),
       ('4','5'),
       ('5','6'),
       ('5','2'),
       ('5','4'),
       ('6','3'),
       ('6','5'),
       ('6','1'),
       ('7','6'),
       ('7','2'),
       ('7','3'),
       ('8','4'),
       ('8','5'),
       ('8','6'),
       ('9','1'),
       ('9','4'),
       ('9','6'),
       ('10','1'),
       ('10','2'),
       ('10','3'),
       ('11','1'),
       ('11','2'),
       ('11','3'),
       ('12','1'),
       ('12','2'),
       ('12','3'),
       ('13','1'),
       ('13','2'),
       ('13','3'),
       ('14','1'),
       ('14','2'),
       ('14','3'),
       ('15','4'),
       ('15','5'),
       ('15','6'),
       ('16','4'),
       ('16','5'),
       ('16','6'),
       ('17','4'),
       ('17','5'),
       ('17','6'),
       ('18','4'),
       ('18','5'),
       ('18','6')
       
       

